import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const CreateLinkForm = dynamic(() => import('../components/create-link'), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div className='flex flex-col justify-center items-center h-screen bg-gray-900 text-white'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <CreateLinkForm />
    </div>
  );
};

export default Home;

